before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq freetds-dev
  - rm -f Gemfile.lock
before_script:
  - git config --global user.email "wallerjake@gmail.com"
  - git config --global user.name "wallerjake"
  - rm -r -f test/remote
  - rm -r -f test/tmp
language: ruby
rvm:
- 2.0.0
addons:
  code_climate:
    repo_token: c94c0c00c0b1bf210f41515822ea072c639ccdb86b7debabc9c60572ce4f39f0
env:
  - RUNNING_ON_CI=true
